#!/usr/bin/env python

import os
from os.path import join, pardir, dirname
import sys

from django.core.management import call_command


# fix PYTHONPATH and DJANGO_SETTINGS for us
# django settings module
DJANGO_SETTINGS_MODULE = 'djangobaseproject.settings'
# pythonpath dirs
PYTHONPATH = [
    join(dirname(__file__), pardir, pardir, pardir),
]

# inject few paths to pythonpath
for p in PYTHONPATH:
    if p not in sys.path:
        sys.path.insert(0, p)

# django needs this env variable
os.environ['DJANGO_SETTINGS_MODULE'] = DJANGO_SETTINGS_MODULE


call_command('cleanup')

# vim: set ft=python:
